### ISSUE TITLE
Meme doesn't exist

### ISSUE THREAD

**Issue by StevenRayno** [KRHS-GameProgramming-2016/Memefinity#4]
![image](https://cloud.githubusercontent.com/assets/22524738/26254703/780a8368-3c85-11e7-9325-22ad055941e8.png)

plz fix

**Comment by Person21** [comment]
Any idea how that happened? Did you properly extract everything from the .zip file? Because I've never seen that happen before. I'm not having any problems with the master file, try re-downloading it and extracting the file once more

**Comment by StevenRayno** [comment]
I must've not extracted it properly, it works now. :3rd_place_medal:
